#!/bin/bash
#-----------------------------------------------------------------------
# Created: 2013-04-28
# $Id: get-whois-ips.sh,v 1.3 2015/06/23 14:04:02 royce Exp royce $
# License: BSD 2-clause
#-----------------------------------------------------------------------

Copyright (c) 2015, Royce D. Williams
All rights reserved.
#-----------------------------------------------------------------------

DATESTAMP=`date '+%Y-%m-%d'`
WHOIS_SRC_FILE="whois-servers_${DATESTAMP}.txt"
WHOIS_DEST_LIST="whois-server-ips.txt"
WHOIS_DEST_LIST_STAMPED="whois-server-ips_${DATESTAMP}.txt"

#-----------------------------------------------------------------------
echo "- Generating: WHOIS ..."

if [ ! -f ${WHOIS_SRC_FILE} ]; then
    echo "- Fetching fresh list of WHOIS servers ..."
    wget -O ${WHOIS_SRC_FILE} http://www.nirsoft.net/whois-servers.txt
else
    echo "- Using already-downloaded WHOIS list ${WHOIS_SRC_FILE}"
fi
if [ ! -f ${WHOIS_SRC_FILE} ]; then
    echo "Error: unable to fetch today's WHOIS list."
    exit 1
fi

if [ ! -f "${WHOIS_DEST_LIST_STAMPED}" ]; then

    echo "# Generated by: $0 - `date`" | tee ${WHOIS_DEST_LIST_STAMPED}

    echo "- Processing ..."
    for host in `cat ${WHOIS_SRC_FILE} | egrep -v '^;' | awk '{print $2}'`; do 
        echo "# $host:"; 
        MYIPS=`host $host|grep 'has address' | awk '{print $4}'`
        for ip in ${MYIPS}; do
            echo "$ip"
        done 
    done | tee -a ${WHOIS_DEST_LIST_STAMPED}

    cp -p ${WHOIS_DEST_LIST_STAMPED} ${WHOIS_DEST_LIST}

else
    echo "- Skipped: ${WHOIS_DEST_LIST_STAMPED} already exists."

fi

#-----------------------------------------------------------------------
